# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountSearchDiaglog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AccountSearchDialog(object):
    def setupUi(self, AccountSearchDialog):
        AccountSearchDialog.setObjectName("AccountSearchDialog")
        AccountSearchDialog.resize(817, 433)
        self.buttonBox = QtWidgets.QDialogButtonBox(AccountSearchDialog)
        self.buttonBox.setGeometry(QtCore.QRect(420, 350, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.checkcheckBox = QtWidgets.QCheckBox(AccountSearchDialog)
        self.checkcheckBox.setGeometry(QtCore.QRect(70, 40, 111, 20))
        self.checkcheckBox.setTabletTracking(False)
        self.checkcheckBox.setAcceptDrops(False)
        self.checkcheckBox.setChecked(True)
        self.checkcheckBox.setObjectName("checkcheckBox")
        self.savecheckBox = QtWidgets.QCheckBox(AccountSearchDialog)
        self.savecheckBox.setGeometry(QtCore.QRect(490, 40, 111, 21))
        self.savecheckBox.setTabletTracking(False)
        self.savecheckBox.setAcceptDrops(False)
        self.savecheckBox.setChecked(True)
        self.savecheckBox.setObjectName("savecheckBox")
        self.layoutWidget = QtWidgets.QWidget(AccountSearchDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 350, 300, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CABlineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.CABlineEdit_2.setObjectName("CABlineEdit_2")
        self.gridLayout_4.addWidget(self.CABlineEdit_2, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.CABcheckBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CABcheckBox_2.setTabletTracking(False)
        self.CABcheckBox_2.setAcceptDrops(False)
        self.CABcheckBox_2.setChecked(False)
        self.CABcheckBox_2.setObjectName("CABcheckBox_2")
        self.gridLayout_4.addWidget(self.CABcheckBox_2, 0, 0, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(AccountSearchDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 90, 313, 176))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkidcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.checkidcomboBox.setObjectName("checkidcomboBox")
        self.checkidcomboBox.addItem("")
        self.checkidcomboBox.addItem("")
        self.checkidcomboBox.addItem("")
        self.gridLayout.addWidget(self.checkidcomboBox, 0, 1, 1, 1)
        self.checkidlineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.checkidlineEdit.setObjectName("checkidlineEdit")
        self.gridLayout.addWidget(self.checkidlineEdit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkbalancecomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.checkbalancecomboBox.setObjectName("checkbalancecomboBox")
        self.checkbalancecomboBox.addItem("")
        self.checkbalancecomboBox.addItem("")
        self.checkbalancecomboBox.addItem("")
        self.checkbalancecomboBox.addItem("")
        self.gridLayout.addWidget(self.checkbalancecomboBox, 1, 1, 1, 1)
        self.checkbalancelineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.checkbalancelineEdit.setObjectName("checkbalancelineEdit")
        self.gridLayout.addWidget(self.checkbalancelineEdit, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.checkopeningdatecomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.checkopeningdatecomboBox.setObjectName("checkopeningdatecomboBox")
        self.checkopeningdatecomboBox.addItem("")
        self.checkopeningdatecomboBox.addItem("")
        self.checkopeningdatecomboBox.addItem("")
        self.checkopeningdatecomboBox.addItem("")
        self.gridLayout.addWidget(self.checkopeningdatecomboBox, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.checkrecentreachcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.checkrecentreachcomboBox.setObjectName("checkrecentreachcomboBox")
        self.checkrecentreachcomboBox.addItem("")
        self.checkrecentreachcomboBox.addItem("")
        self.checkrecentreachcomboBox.addItem("")
        self.checkrecentreachcomboBox.addItem("")
        self.checkrecentreachcomboBox.addItem("")
        self.gridLayout.addWidget(self.checkrecentreachcomboBox, 3, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.checkoverdraftcomboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.checkoverdraftcomboBox.setObjectName("checkoverdraftcomboBox")
        self.checkoverdraftcomboBox.addItem("")
        self.checkoverdraftcomboBox.addItem("")
        self.checkoverdraftcomboBox.addItem("")
        self.checkoverdraftcomboBox.addItem("")
        self.gridLayout.addWidget(self.checkoverdraftcomboBox, 4, 1, 1, 1)
        self.checkoverdraftlineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.checkoverdraftlineEdit.setObjectName("checkoverdraftlineEdit")
        self.gridLayout.addWidget(self.checkoverdraftlineEdit, 4, 2, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(AccountSearchDialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(440, 90, 313, 212))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.saveidcomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.saveidcomboBox.setObjectName("saveidcomboBox")
        self.saveidcomboBox.addItem("")
        self.saveidcomboBox.addItem("")
        self.saveidcomboBox.addItem("")
        self.gridLayout_2.addWidget(self.saveidcomboBox, 0, 1, 1, 1)
        self.saveidlineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.saveidlineEdit.setObjectName("saveidlineEdit")
        self.gridLayout_2.addWidget(self.saveidlineEdit, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.savebalancecomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.savebalancecomboBox.setObjectName("savebalancecomboBox")
        self.savebalancecomboBox.addItem("")
        self.savebalancecomboBox.addItem("")
        self.savebalancecomboBox.addItem("")
        self.savebalancecomboBox.addItem("")
        self.gridLayout_2.addWidget(self.savebalancecomboBox, 1, 1, 1, 1)
        self.savebalancelineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.savebalancelineEdit.setObjectName("savebalancelineEdit")
        self.gridLayout_2.addWidget(self.savebalancelineEdit, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.saveopeningdatecomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.saveopeningdatecomboBox.setObjectName("saveopeningdatecomboBox")
        self.saveopeningdatecomboBox.addItem("")
        self.saveopeningdatecomboBox.addItem("")
        self.saveopeningdatecomboBox.addItem("")
        self.saveopeningdatecomboBox.addItem("")
        self.gridLayout_2.addWidget(self.saveopeningdatecomboBox, 2, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.saverecentreachcomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.saverecentreachcomboBox.setObjectName("saverecentreachcomboBox")
        self.saverecentreachcomboBox.addItem("")
        self.saverecentreachcomboBox.addItem("")
        self.saverecentreachcomboBox.addItem("")
        self.saverecentreachcomboBox.addItem("")
        self.saverecentreachcomboBox.addItem("")
        self.gridLayout_2.addWidget(self.saverecentreachcomboBox, 3, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.saveratecomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.saveratecomboBox.setObjectName("saveratecomboBox")
        self.saveratecomboBox.addItem("")
        self.saveratecomboBox.addItem("")
        self.saveratecomboBox.addItem("")
        self.saveratecomboBox.addItem("")
        self.gridLayout_2.addWidget(self.saveratecomboBox, 4, 1, 1, 1)
        self.saveratelineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.saveratelineEdit.setObjectName("saveratelineEdit")
        self.gridLayout_2.addWidget(self.saveratelineEdit, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.savecurrencycomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.savecurrencycomboBox.setObjectName("savecurrencycomboBox")
        self.savecurrencycomboBox.addItem("")
        self.savecurrencycomboBox.addItem("")
        self.savecurrencycomboBox.addItem("")
        self.savecurrencycomboBox.addItem("")
        self.gridLayout_2.addWidget(self.savecurrencycomboBox, 5, 1, 1, 2)
        self.layoutWidget3 = QtWidgets.QWidget(AccountSearchDialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 290, 300, 51))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CABlineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.CABlineEdit.setObjectName("CABlineEdit")
        self.gridLayout_3.addWidget(self.CABlineEdit, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.CABcheckBox = QtWidgets.QCheckBox(self.layoutWidget3)
        self.CABcheckBox.setTabletTracking(False)
        self.CABcheckBox.setAcceptDrops(False)
        self.CABcheckBox.setChecked(False)
        self.CABcheckBox.setObjectName("CABcheckBox")
        self.gridLayout_3.addWidget(self.CABcheckBox, 0, 0, 1, 2)

        self.retranslateUi(AccountSearchDialog)
        self.buttonBox.accepted.connect(AccountSearchDialog.accept)
        self.buttonBox.rejected.connect(AccountSearchDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AccountSearchDialog)

    def retranslateUi(self, AccountSearchDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountSearchDialog.setWindowTitle(_translate("AccountSearchDialog", "AccountSearchDialog"))
        self.checkcheckBox.setText(_translate("AccountSearchDialog", "查询支票账户"))
        self.savecheckBox.setText(_translate("AccountSearchDialog", "查询储蓄账户"))
        self.label_14.setText(_translate("AccountSearchDialog", "身份证号"))
        self.CABcheckBox_2.setText(_translate("AccountSearchDialog", "查询顾客所有账户 必须提供完整的身份证号"))
        self.label.setText(_translate("AccountSearchDialog", "账户号"))
        self.checkidcomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.checkidcomboBox.setItemText(1, _translate("AccountSearchDialog", "是"))
        self.checkidcomboBox.setItemText(2, _translate("AccountSearchDialog", "包含"))
        self.label_2.setText(_translate("AccountSearchDialog", "余额"))
        self.checkbalancecomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.checkbalancecomboBox.setItemText(1, _translate("AccountSearchDialog", "等于"))
        self.checkbalancecomboBox.setItemText(2, _translate("AccountSearchDialog", "大于"))
        self.checkbalancecomboBox.setItemText(3, _translate("AccountSearchDialog", "小于"))
        self.label_3.setText(_translate("AccountSearchDialog", "开户日期"))
        self.checkopeningdatecomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.checkopeningdatecomboBox.setItemText(1, _translate("AccountSearchDialog", "一年之内"))
        self.checkopeningdatecomboBox.setItemText(2, _translate("AccountSearchDialog", "两年之内"))
        self.checkopeningdatecomboBox.setItemText(3, _translate("AccountSearchDialog", "两年以上"))
        self.label_4.setText(_translate("AccountSearchDialog", "最近访问日期日期"))
        self.checkrecentreachcomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.checkrecentreachcomboBox.setItemText(1, _translate("AccountSearchDialog", "一个月之内"))
        self.checkrecentreachcomboBox.setItemText(2, _translate("AccountSearchDialog", "六个月之内"))
        self.checkrecentreachcomboBox.setItemText(3, _translate("AccountSearchDialog", "一年之内"))
        self.checkrecentreachcomboBox.setItemText(4, _translate("AccountSearchDialog", "一年以上"))
        self.label_6.setText(_translate("AccountSearchDialog", "透支额度"))
        self.checkoverdraftcomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.checkoverdraftcomboBox.setItemText(1, _translate("AccountSearchDialog", "等于"))
        self.checkoverdraftcomboBox.setItemText(2, _translate("AccountSearchDialog", "大于"))
        self.checkoverdraftcomboBox.setItemText(3, _translate("AccountSearchDialog", "小于"))
        self.label_7.setText(_translate("AccountSearchDialog", "账户号"))
        self.saveidcomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.saveidcomboBox.setItemText(1, _translate("AccountSearchDialog", "是"))
        self.saveidcomboBox.setItemText(2, _translate("AccountSearchDialog", "包含"))
        self.label_8.setText(_translate("AccountSearchDialog", "余额"))
        self.savebalancecomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.savebalancecomboBox.setItemText(1, _translate("AccountSearchDialog", "等于"))
        self.savebalancecomboBox.setItemText(2, _translate("AccountSearchDialog", "大于"))
        self.savebalancecomboBox.setItemText(3, _translate("AccountSearchDialog", "小于"))
        self.label_9.setText(_translate("AccountSearchDialog", "开户日期"))
        self.saveopeningdatecomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.saveopeningdatecomboBox.setItemText(1, _translate("AccountSearchDialog", "一年之内"))
        self.saveopeningdatecomboBox.setItemText(2, _translate("AccountSearchDialog", "两年之内"))
        self.saveopeningdatecomboBox.setItemText(3, _translate("AccountSearchDialog", "两年以上"))
        self.label_10.setText(_translate("AccountSearchDialog", "最近访问日期日期"))
        self.saverecentreachcomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.saverecentreachcomboBox.setItemText(1, _translate("AccountSearchDialog", "一个月之内"))
        self.saverecentreachcomboBox.setItemText(2, _translate("AccountSearchDialog", "六个月之内"))
        self.saverecentreachcomboBox.setItemText(3, _translate("AccountSearchDialog", "一年之内"))
        self.saverecentreachcomboBox.setItemText(4, _translate("AccountSearchDialog", "一年以上"))
        self.label_11.setText(_translate("AccountSearchDialog", "利率"))
        self.saveratecomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.saveratecomboBox.setItemText(1, _translate("AccountSearchDialog", "等于"))
        self.saveratecomboBox.setItemText(2, _translate("AccountSearchDialog", "大于"))
        self.saveratecomboBox.setItemText(3, _translate("AccountSearchDialog", "小于"))
        self.label_12.setText(_translate("AccountSearchDialog", "货币类型"))
        self.savecurrencycomboBox.setItemText(0, _translate("AccountSearchDialog", "不限"))
        self.savecurrencycomboBox.setItemText(1, _translate("AccountSearchDialog", "RMB"))
        self.savecurrencycomboBox.setItemText(2, _translate("AccountSearchDialog", "dollar"))
        self.savecurrencycomboBox.setItemText(3, _translate("AccountSearchDialog", "others"))
        self.label_13.setText(_translate("AccountSearchDialog", "账户号"))
        self.CABcheckBox.setText(_translate("AccountSearchDialog", "查询账户所有人 必须提供完整的账户号"))

