# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountAddDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AccountAddDialog(object):
    def setupUi(self, AccountAddDialog):
        AccountAddDialog.setObjectName("AccountAddDialog")
        AccountAddDialog.resize(590, 344)
        self.widget = QtWidgets.QWidget(AccountAddDialog)
        self.widget.setGeometry(QtCore.QRect(50, 30, 487, 276))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.accountlineEdit = QtWidgets.QLineEdit(self.widget)
        self.accountlineEdit.setObjectName("accountlineEdit")
        self.gridLayout.addWidget(self.accountlineEdit, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.ratelineEdit = QtWidgets.QLineEdit(self.widget)
        self.ratelineEdit.setObjectName("ratelineEdit")
        self.gridLayout.addWidget(self.ratelineEdit, 0, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.clientlineEdit = QtWidgets.QLineEdit(self.widget)
        self.clientlineEdit.setObjectName("clientlineEdit")
        self.gridLayout.addWidget(self.clientlineEdit, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 2)
        self.typelineEdit = QtWidgets.QLineEdit(self.widget)
        self.typelineEdit.setObjectName("typelineEdit")
        self.gridLayout.addWidget(self.typelineEdit, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.overdraftlineEdit = QtWidgets.QLineEdit(self.widget)
        self.overdraftlineEdit.setObjectName("overdraftlineEdit")
        self.gridLayout.addWidget(self.overdraftlineEdit, 2, 3, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.branchlineEdit = QtWidgets.QLineEdit(self.widget)
        self.branchlineEdit.setObjectName("branchlineEdit")
        self.gridLayout.addWidget(self.branchlineEdit, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 1)

        self.retranslateUi(AccountAddDialog)
        self.buttonBox.accepted.connect(AccountAddDialog.accept)
        self.buttonBox.rejected.connect(AccountAddDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AccountAddDialog)

    def retranslateUi(self, AccountAddDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountAddDialog.setWindowTitle(_translate("AccountAddDialog", "AccountAddDialog"))
        self.label_2.setText(_translate("AccountAddDialog", "此界面供开户和增加开户人员使用，必须输入完整的客户身份证号和账户号"))
        self.label_3.setText(_translate("AccountAddDialog", "账户号可以存在于数据库中，但是账户号、身份证号和开户网点不能完全相同"))
        self.label_4.setText(_translate("AccountAddDialog", "客户信息、开户网点必须已经存储于数据库中，且不会修改已存储的账户信息"))
        self.label_14.setText(_translate("AccountAddDialog", "账户号"))
        self.label_10.setText(_translate("AccountAddDialog", "储蓄账户的利率"))
        self.label.setText(_translate("AccountAddDialog", "客户身份证号"))
        self.label_13.setText(_translate("AccountAddDialog", "储蓄账户的货币类型"))
        self.label_9.setText(_translate("AccountAddDialog", "账户类型"))
        self.comboBox.setItemText(0, _translate("AccountAddDialog", "储蓄账户"))
        self.comboBox.setItemText(1, _translate("AccountAddDialog", "支票账户"))
        self.label_8.setText(_translate("AccountAddDialog", "支票账户的透支额"))
        self.label_12.setText(_translate("AccountAddDialog", "开户网点"))

