# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AccountForm(object):
    def setupUi(self, AccountForm):
        AccountForm.setObjectName("AccountForm")
        AccountForm.resize(817, 645)
        self.splitter = QtWidgets.QSplitter(AccountForm)
        self.splitter.setGeometry(QtCore.QRect(70, 580, 401, 32))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.AddBtn = QtWidgets.QPushButton(self.splitter)
        self.AddBtn.setObjectName("AddBtn")
        self.DeleteBtn = QtWidgets.QPushButton(self.splitter)
        self.DeleteBtn.setObjectName("DeleteBtn")
        self.UpdateBtn = QtWidgets.QPushButton(self.splitter)
        self.UpdateBtn.setObjectName("UpdateBtn")
        self.SearchBtn = QtWidgets.QPushButton(self.splitter)
        self.SearchBtn.setObjectName("SearchBtn")
        self.messagetextEdit = QtWidgets.QTextEdit(AccountForm)
        self.messagetextEdit.setGeometry(QtCore.QRect(550, 570, 221, 51))
        self.messagetextEdit.setObjectName("messagetextEdit")
        self.label_3 = QtWidgets.QLabel(AccountForm)
        self.label_3.setGeometry(QtCore.QRect(621, 30, 91, 20))
        self.label_3.setObjectName("label_3")
        self.othertable = QtWidgets.QTableWidget(AccountForm)
        self.othertable.setGeometry(QtCore.QRect(541, 57, 256, 211))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.othertable.setFont(font)
        self.othertable.setObjectName("othertable")
        self.othertable.setColumnCount(0)
        self.othertable.setRowCount(0)
        self.othertable_2 = QtWidgets.QTableWidget(AccountForm)
        self.othertable_2.setGeometry(QtCore.QRect(541, 307, 256, 211))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.othertable_2.setFont(font)
        self.othertable_2.setObjectName("othertable_2")
        self.othertable_2.setColumnCount(0)
        self.othertable_2.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(AccountForm)
        self.label_4.setGeometry(QtCore.QRect(620, 280, 111, 18))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(AccountForm)
        self.widget.setGeometry(QtCore.QRect(20, 30, 501, 511))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkingtable = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkingtable.setFont(font)
        self.checkingtable.setObjectName("checkingtable")
        self.checkingtable.setColumnCount(0)
        self.checkingtable.setRowCount(0)
        self.gridLayout.addWidget(self.checkingtable, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.savingtable = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.savingtable.setFont(font)
        self.savingtable.setObjectName("savingtable")
        self.savingtable.setColumnCount(0)
        self.savingtable.setRowCount(0)
        self.gridLayout.addWidget(self.savingtable, 1, 1, 1, 1)

        self.retranslateUi(AccountForm)
        QtCore.QMetaObject.connectSlotsByName(AccountForm)

    def retranslateUi(self, AccountForm):
        _translate = QtCore.QCoreApplication.translate
        AccountForm.setWindowTitle(_translate("AccountForm", "AccountForm"))
        self.AddBtn.setText(_translate("AccountForm", "Add"))
        self.DeleteBtn.setText(_translate("AccountForm", "Delete"))
        self.UpdateBtn.setText(_translate("AccountForm", "Update"))
        self.SearchBtn.setText(_translate("AccountForm", "Search"))
        self.label_3.setText(_translate("AccountForm", "查询账户所有人"))
        self.label_4.setText(_translate("AccountForm", "查询客户所有账户"))
        self.label.setText(_translate("AccountForm", "支票账户"))
        self.label_2.setText(_translate("AccountForm", "储蓄账户"))

