# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountUpdateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AccountUpdateDialog(object):
    def setupUi(self, AccountUpdateDialog):
        AccountUpdateDialog.setObjectName("AccountUpdateDialog")
        AccountUpdateDialog.resize(652, 364)
        self.buttonBox = QtWidgets.QDialogButtonBox(AccountUpdateDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-120, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(AccountUpdateDialog)
        self.label_3.setGeometry(QtCore.QRect(440, 40, 61, 18))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(AccountUpdateDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 70, 255, 242))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.typecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.typecheckBox.setObjectName("typecheckBox")
        self.verticalLayout_5.addWidget(self.typecheckBox)
        self.ratecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.ratecheckBox.setObjectName("ratecheckBox")
        self.verticalLayout_5.addWidget(self.ratecheckBox)
        self.currencycheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.currencycheckBox.setObjectName("currencycheckBox")
        self.verticalLayout_5.addWidget(self.currencycheckBox)
        self.overdraftcheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.overdraftcheckBox.setObjectName("overdraftcheckBox")
        self.verticalLayout_5.addWidget(self.overdraftcheckBox)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.ratelineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ratelineEdit.setObjectName("ratelineEdit")
        self.verticalLayout_4.addWidget(self.ratelineEdit)
        self.currencylineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.currencylineEdit.setObjectName("currencylineEdit")
        self.verticalLayout_4.addWidget(self.currencylineEdit)
        self.overdraftlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.overdraftlineEdit.setObjectName("overdraftlineEdit")
        self.verticalLayout_4.addWidget(self.overdraftlineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.widget = QtWidgets.QWidget(AccountUpdateDialog)
        self.widget.setGeometry(QtCore.QRect(43, 80, 243, 81))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.accountlineEdit = QtWidgets.QLineEdit(self.widget)
        self.accountlineEdit.setObjectName("accountlineEdit")
        self.gridLayout_2.addWidget(self.accountlineEdit, 1, 1, 1, 1)

        self.retranslateUi(AccountUpdateDialog)
        self.buttonBox.accepted.connect(AccountUpdateDialog.accept)
        self.buttonBox.rejected.connect(AccountUpdateDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AccountUpdateDialog)

    def retranslateUi(self, AccountUpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountUpdateDialog.setWindowTitle(_translate("AccountUpdateDialog", "AccountUpdateDialog"))
        self.label_3.setText(_translate("AccountUpdateDialog", "更改情况"))
        self.typecheckBox.setText(_translate("AccountUpdateDialog", "账户类型"))
        self.ratecheckBox.setText(_translate("AccountUpdateDialog", "储蓄账户利率"))
        self.currencycheckBox.setText(_translate("AccountUpdateDialog", "储蓄账户货币类型"))
        self.overdraftcheckBox.setText(_translate("AccountUpdateDialog", "支票账户透支额"))
        self.comboBox.setItemText(0, _translate("AccountUpdateDialog", "储蓄账户"))
        self.comboBox.setItemText(1, _translate("AccountUpdateDialog", "支票账户"))
        self.label_2.setText(_translate("AccountUpdateDialog", "           更新条件 需要完整账户号"))
        self.label.setText(_translate("AccountUpdateDialog", "需要更改的账户号"))

