# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BusinessAddDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BusinessAddDialog(object):
    def setupUi(self, BusinessAddDialog):
        BusinessAddDialog.setObjectName("BusinessAddDialog")
        BusinessAddDialog.resize(730, 451)
        self.widget = QtWidgets.QWidget(BusinessAddDialog)
        self.widget.setGeometry(QtCore.QRect(40, 40, 641, 381))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.loancheckBox = QtWidgets.QCheckBox(self.widget)
        self.loancheckBox.setObjectName("loancheckBox")
        self.gridLayout.addWidget(self.loancheckBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.loanidlineEdit = QtWidgets.QLineEdit(self.widget)
        self.loanidlineEdit.setObjectName("loanidlineEdit")
        self.gridLayout.addWidget(self.loanidlineEdit, 0, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.loanaccountlineEdit = QtWidgets.QLineEdit(self.widget)
        self.loanaccountlineEdit.setObjectName("loanaccountlineEdit")
        self.gridLayout.addWidget(self.loanaccountlineEdit, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.loanclientlineEdit = QtWidgets.QLineEdit(self.widget)
        self.loanclientlineEdit.setObjectName("loanclientlineEdit")
        self.gridLayout.addWidget(self.loanclientlineEdit, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.loantotalidlineEdit = QtWidgets.QLineEdit(self.widget)
        self.loantotalidlineEdit.setObjectName("loantotalidlineEdit")
        self.gridLayout.addWidget(self.loantotalidlineEdit, 1, 5, 1, 1)
        self.grantcheckBox = QtWidgets.QCheckBox(self.widget)
        self.grantcheckBox.setObjectName("grantcheckBox")
        self.gridLayout.addWidget(self.grantcheckBox, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 2)
        self.grantidlineEdit = QtWidgets.QLineEdit(self.widget)
        self.grantidlineEdit.setObjectName("grantidlineEdit")
        self.gridLayout.addWidget(self.grantidlineEdit, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 4, 1, 1)
        self.grantloanidlineEdit = QtWidgets.QLineEdit(self.widget)
        self.grantloanidlineEdit.setObjectName("grantloanidlineEdit")
        self.gridLayout.addWidget(self.grantloanidlineEdit, 2, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 2)
        self.grantamountlineEdit = QtWidgets.QLineEdit(self.widget)
        self.grantamountlineEdit.setObjectName("grantamountlineEdit")
        self.gridLayout.addWidget(self.grantamountlineEdit, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 4, 1, 1)
        self.grantcomboBox = QtWidgets.QComboBox(self.widget)
        self.grantcomboBox.setObjectName("grantcomboBox")
        self.grantcomboBox.addItem("")
        self.grantcomboBox.addItem("")
        self.gridLayout.addWidget(self.grantcomboBox, 3, 5, 1, 1)
        self.repaycheckBox = QtWidgets.QCheckBox(self.widget)
        self.repaycheckBox.setObjectName("repaycheckBox")
        self.gridLayout.addWidget(self.repaycheckBox, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 1, 1, 2)
        self.repayidlineEdit = QtWidgets.QLineEdit(self.widget)
        self.repayidlineEdit.setObjectName("repayidlineEdit")
        self.gridLayout.addWidget(self.repayidlineEdit, 4, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 4, 1, 1)
        self.repayloanidlineEdit = QtWidgets.QLineEdit(self.widget)
        self.repayloanidlineEdit.setObjectName("repayloanidlineEdit")
        self.gridLayout.addWidget(self.repayloanidlineEdit, 4, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 1, 1, 2)
        self.repayamountlineEdit = QtWidgets.QLineEdit(self.widget)
        self.repayamountlineEdit.setObjectName("repayamountlineEdit")
        self.gridLayout.addWidget(self.repayamountlineEdit, 5, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 4, 1, 1)
        self.repaycomboBox = QtWidgets.QComboBox(self.widget)
        self.repaycomboBox.setObjectName("repaycomboBox")
        self.repaycomboBox.addItem("")
        self.repaycomboBox.addItem("")
        self.gridLayout.addWidget(self.repaycomboBox, 5, 5, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 5, 1, 1)

        self.retranslateUi(BusinessAddDialog)
        self.buttonBox.accepted.connect(BusinessAddDialog.accept)
        self.buttonBox.rejected.connect(BusinessAddDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BusinessAddDialog)

    def retranslateUi(self, BusinessAddDialog):
        _translate = QtCore.QCoreApplication.translate
        BusinessAddDialog.setWindowTitle(_translate("BusinessAddDialog", "BusinessAddDialog"))
        self.loancheckBox.setText(_translate("BusinessAddDialog", "新增贷款"))
        self.label.setText(_translate("BusinessAddDialog", "贷款号"))
        self.label_2.setText(_translate("BusinessAddDialog", "贷款账户号"))
        self.label_3.setText(_translate("BusinessAddDialog", "贷款人身份证号"))
        self.label_4.setText(_translate("BusinessAddDialog", "贷款总额"))
        self.grantcheckBox.setText(_translate("BusinessAddDialog", "新增贷款发放"))
        self.label_7.setText(_translate("BusinessAddDialog", "贷款发放号"))
        self.label_5.setText(_translate("BusinessAddDialog", "贷款号"))
        self.label_6.setText(_translate("BusinessAddDialog", "发放总额"))
        self.label_8.setText(_translate("BusinessAddDialog", "发放方式"))
        self.grantcomboBox.setItemText(0, _translate("BusinessAddDialog", "现金"))
        self.grantcomboBox.setItemText(1, _translate("BusinessAddDialog", "转账"))
        self.repaycheckBox.setText(_translate("BusinessAddDialog", "新增贷款还款"))
        self.label_12.setText(_translate("BusinessAddDialog", "贷款还款号"))
        self.label_11.setText(_translate("BusinessAddDialog", "贷款号"))
        self.label_10.setText(_translate("BusinessAddDialog", "还款总额"))
        self.label_9.setText(_translate("BusinessAddDialog", "还款方式"))
        self.repaycomboBox.setItemText(0, _translate("BusinessAddDialog", "现金"))
        self.repaycomboBox.setItemText(1, _translate("BusinessAddDialog", "转账"))

