# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientDeleteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientDeleteDialog(object):
    def setupUi(self, ClientDeleteDialog):
        ClientDeleteDialog.setObjectName("ClientDeleteDialog")
        ClientDeleteDialog.resize(606, 330)
        self.buttonBox = QtWidgets.QDialogButtonBox(ClientDeleteDialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 280, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(ClientDeleteDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 90, 232, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.idcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.idcomboBox.setObjectName("idcomboBox")
        self.idcomboBox.addItem("")
        self.idcomboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.idcomboBox)
        self.idlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.idlineEdit.setObjectName("idlineEdit")
        self.horizontalLayout_2.addWidget(self.idlineEdit)
        self.layoutWidget_2 = QtWidgets.QWidget(ClientDeleteDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(150, 120, 232, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.telcomboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.telcomboBox.setObjectName("telcomboBox")
        self.telcomboBox.addItem("")
        self.telcomboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.telcomboBox)
        self.tellineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.tellineEdit.setObjectName("tellineEdit")
        self.horizontalLayout_3.addWidget(self.tellineEdit)
        self.layoutWidget_3 = QtWidgets.QWidget(ClientDeleteDialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(150, 150, 232, 32))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.addresscomboBox = QtWidgets.QComboBox(self.layoutWidget_3)
        self.addresscomboBox.setObjectName("addresscomboBox")
        self.addresscomboBox.addItem("")
        self.addresscomboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.addresscomboBox)
        self.addresslineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.addresslineEdit.setObjectName("addresslineEdit")
        self.horizontalLayout_4.addWidget(self.addresslineEdit)
        self.layoutWidget_4 = QtWidgets.QWidget(ClientDeleteDialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(150, 180, 232, 32))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cnamecomboBox = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cnamecomboBox.setObjectName("cnamecomboBox")
        self.cnamecomboBox.addItem("")
        self.cnamecomboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.cnamecomboBox)
        self.cnamelineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.cnamelineEdit.setObjectName("cnamelineEdit")
        self.horizontalLayout_5.addWidget(self.cnamelineEdit)
        self.textBrowser = QtWidgets.QTextBrowser(ClientDeleteDialog)
        self.textBrowser.setGeometry(QtCore.QRect(440, 120, 111, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.label_6 = QtWidgets.QLabel(ClientDeleteDialog)
        self.label_6.setGeometry(QtCore.QRect(474, 100, 41, 16))
        self.label_6.setObjectName("label_6")
        self.checkBox2 = QtWidgets.QCheckBox(ClientDeleteDialog)
        self.checkBox2.setGeometry(QtCore.QRect(110, 220, 171, 20))
        self.checkBox2.setObjectName("checkBox2")
        self.checkBox1 = QtWidgets.QCheckBox(ClientDeleteDialog)
        self.checkBox1.setGeometry(QtCore.QRect(110, 30, 171, 20))
        self.checkBox1.setObjectName("checkBox1")
        self.widget = QtWidgets.QWidget(ClientDeleteDialog)
        self.widget.setGeometry(QtCore.QRect(150, 60, 232, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.namecomboBox = QtWidgets.QComboBox(self.widget)
        self.namecomboBox.setObjectName("namecomboBox")
        self.namecomboBox.addItem("")
        self.namecomboBox.addItem("")
        self.horizontalLayout.addWidget(self.namecomboBox)
        self.namelineEdit = QtWidgets.QLineEdit(self.widget)
        self.namelineEdit.setObjectName("namelineEdit")
        self.horizontalLayout.addWidget(self.namelineEdit)

        self.retranslateUi(ClientDeleteDialog)
        self.buttonBox.accepted.connect(ClientDeleteDialog.accept)
        self.buttonBox.rejected.connect(ClientDeleteDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ClientDeleteDialog)

    def retranslateUi(self, ClientDeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        ClientDeleteDialog.setWindowTitle(_translate("ClientDeleteDialog", "ClientDeleteDialog"))
        self.label_2.setText(_translate("ClientDeleteDialog", "身份证号"))
        self.idcomboBox.setItemText(0, _translate("ClientDeleteDialog", "含有"))
        self.idcomboBox.setItemText(1, _translate("ClientDeleteDialog", "是"))
        self.label_3.setText(_translate("ClientDeleteDialog", "电话"))
        self.telcomboBox.setItemText(0, _translate("ClientDeleteDialog", "含有"))
        self.telcomboBox.setItemText(1, _translate("ClientDeleteDialog", "是"))
        self.label_4.setText(_translate("ClientDeleteDialog", "地址"))
        self.addresscomboBox.setItemText(0, _translate("ClientDeleteDialog", "含有"))
        self.addresscomboBox.setItemText(1, _translate("ClientDeleteDialog", "是"))
        self.label_5.setText(_translate("ClientDeleteDialog", "联系人姓名"))
        self.cnamecomboBox.setItemText(0, _translate("ClientDeleteDialog", "含有"))
        self.cnamecomboBox.setItemText(1, _translate("ClientDeleteDialog", "是"))
        self.textBrowser.setHtml(_translate("ClientDeleteDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">不允许删除存在关联账户或贷款记录的用户</p></body></html>"))
        self.label_6.setText(_translate("ClientDeleteDialog", "提示框"))
        self.checkBox2.setText(_translate("ClientDeleteDialog", "删除字段缺失的记录"))
        self.checkBox1.setText(_translate("ClientDeleteDialog", "删除满足下述条件的记录"))
        self.label.setText(_translate("ClientDeleteDialog", "姓名"))
        self.namecomboBox.setItemText(0, _translate("ClientDeleteDialog", "含有"))
        self.namecomboBox.setItemText(1, _translate("ClientDeleteDialog", "是"))

