# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUpdateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientUpdateDialog(object):
    def setupUi(self, ClientUpdateDialog):
        ClientUpdateDialog.setObjectName("ClientUpdateDialog")
        ClientUpdateDialog.resize(735, 445)
        self.buttonBox = QtWidgets.QDialogButtonBox(ClientUpdateDialog)
        self.buttonBox.setGeometry(QtCore.QRect(370, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(ClientUpdateDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 314, 312))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.idcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.idcomboBox.setObjectName("idcomboBox")
        self.idcomboBox.addItem("")
        self.idcomboBox.addItem("")
        self.idcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.idcomboBox)
        self.namecomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.namecomboBox.setObjectName("namecomboBox")
        self.namecomboBox.addItem("")
        self.namecomboBox.addItem("")
        self.namecomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.namecomboBox)
        self.addresscomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.addresscomboBox.setObjectName("addresscomboBox")
        self.addresscomboBox.addItem("")
        self.addresscomboBox.addItem("")
        self.addresscomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.addresscomboBox)
        self.telcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.telcomboBox.setObjectName("telcomboBox")
        self.telcomboBox.addItem("")
        self.telcomboBox.addItem("")
        self.telcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.telcomboBox)
        self.relationcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.relationcomboBox.setObjectName("relationcomboBox")
        self.relationcomboBox.addItem("")
        self.relationcomboBox.addItem("")
        self.relationcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.relationcomboBox)
        self.cnamecomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.cnamecomboBox.setObjectName("cnamecomboBox")
        self.cnamecomboBox.addItem("")
        self.cnamecomboBox.addItem("")
        self.cnamecomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.cnamecomboBox)
        self.cemailcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.cemailcomboBox.setObjectName("cemailcomboBox")
        self.cemailcomboBox.addItem("")
        self.cemailcomboBox.addItem("")
        self.cemailcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.cemailcomboBox)
        self.ctelcomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.ctelcomboBox.setObjectName("ctelcomboBox")
        self.ctelcomboBox.addItem("")
        self.ctelcomboBox.addItem("")
        self.ctelcomboBox.addItem("")
        self.verticalLayout_2.addWidget(self.ctelcomboBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.idlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.idlineEdit.setObjectName("idlineEdit")
        self.verticalLayout_3.addWidget(self.idlineEdit)
        self.namelineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.namelineEdit.setObjectName("namelineEdit")
        self.verticalLayout_3.addWidget(self.namelineEdit)
        self.addresslineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.addresslineEdit.setObjectName("addresslineEdit")
        self.verticalLayout_3.addWidget(self.addresslineEdit)
        self.tellineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.tellineEdit.setObjectName("tellineEdit")
        self.verticalLayout_3.addWidget(self.tellineEdit)
        self.cnamelineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cnamelineEdit.setObjectName("cnamelineEdit")
        self.verticalLayout_3.addWidget(self.cnamelineEdit)
        self.relationlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.relationlineEdit.setObjectName("relationlineEdit")
        self.verticalLayout_3.addWidget(self.relationlineEdit)
        self.cemaillineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cemaillineEdit.setObjectName("cemaillineEdit")
        self.verticalLayout_3.addWidget(self.cemaillineEdit)
        self.ctellineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ctellineEdit.setObjectName("ctellineEdit")
        self.verticalLayout_3.addWidget(self.ctellineEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ClientUpdateDialog)
        self.label_3.setGeometry(QtCore.QRect(530, 50, 61, 18))
        self.label_3.setObjectName("label_3")
        self.layoutWidget1 = QtWidgets.QWidget(ClientUpdateDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 80, 311, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.idcheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.idcheckBox.setObjectName("idcheckBox")
        self.verticalLayout_5.addWidget(self.idcheckBox)
        self.namecheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.namecheckBox.setObjectName("namecheckBox")
        self.verticalLayout_5.addWidget(self.namecheckBox)
        self.addresscheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.addresscheckBox.setObjectName("addresscheckBox")
        self.verticalLayout_5.addWidget(self.addresscheckBox)
        self.telcheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.telcheckBox.setObjectName("telcheckBox")
        self.verticalLayout_5.addWidget(self.telcheckBox)
        self.cnamecheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cnamecheckBox.setObjectName("cnamecheckBox")
        self.verticalLayout_5.addWidget(self.cnamecheckBox)
        self.relationcheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.relationcheckBox.setObjectName("relationcheckBox")
        self.verticalLayout_5.addWidget(self.relationcheckBox)
        self.cemailcheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cemailcheckBox.setObjectName("cemailcheckBox")
        self.verticalLayout_5.addWidget(self.cemailcheckBox)
        self.ctelcheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ctelcheckBox.setObjectName("ctelcheckBox")
        self.verticalLayout_5.addWidget(self.ctelcheckBox)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.idlineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.idlineEdit_2.setObjectName("idlineEdit_2")
        self.verticalLayout_4.addWidget(self.idlineEdit_2)
        self.namelineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.namelineEdit_2.setObjectName("namelineEdit_2")
        self.verticalLayout_4.addWidget(self.namelineEdit_2)
        self.addresslineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.addresslineEdit_2.setObjectName("addresslineEdit_2")
        self.verticalLayout_4.addWidget(self.addresslineEdit_2)
        self.tellineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.tellineEdit_2.setObjectName("tellineEdit_2")
        self.verticalLayout_4.addWidget(self.tellineEdit_2)
        self.cnamelineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.cnamelineEdit_2.setObjectName("cnamelineEdit_2")
        self.verticalLayout_4.addWidget(self.cnamelineEdit_2)
        self.relationlineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.relationlineEdit_2.setObjectName("relationlineEdit_2")
        self.verticalLayout_4.addWidget(self.relationlineEdit_2)
        self.cemaillineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.cemaillineEdit_2.setObjectName("cemaillineEdit_2")
        self.verticalLayout_4.addWidget(self.cemaillineEdit_2)
        self.ctellineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ctellineEdit_2.setObjectName("ctellineEdit_2")
        self.verticalLayout_4.addWidget(self.ctellineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(ClientUpdateDialog)
        self.buttonBox.accepted.connect(ClientUpdateDialog.accept)
        self.buttonBox.rejected.connect(ClientUpdateDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ClientUpdateDialog)

    def retranslateUi(self, ClientUpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        ClientUpdateDialog.setWindowTitle(_translate("ClientUpdateDialog", "ClientUpdateDialog"))
        self.label_2.setText(_translate("ClientUpdateDialog", "           更新条件 \"含有\"和\"是\"的空白代表无限制"))
        self.label.setText(_translate("ClientUpdateDialog", "身份证号"))
        self.label_13.setText(_translate("ClientUpdateDialog", "姓名"))
        self.label_10.setText(_translate("ClientUpdateDialog", "地址"))
        self.label_14.setText(_translate("ClientUpdateDialog", "联系方式"))
        self.label_8.setText(_translate("ClientUpdateDialog", "联系人姓名"))
        self.label_12.setText(_translate("ClientUpdateDialog", "与联系人关系"))
        self.label_9.setText(_translate("ClientUpdateDialog", "联系人邮箱"))
        self.label_11.setText(_translate("ClientUpdateDialog", "联系人联系方式"))
        self.idcomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.idcomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.idcomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.namecomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.namecomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.namecomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.addresscomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.addresscomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.addresscomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.telcomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.telcomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.telcomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.relationcomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.relationcomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.relationcomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.cnamecomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.cnamecomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.cnamecomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.cemailcomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.cemailcomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.cemailcomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.ctelcomboBox.setItemText(0, _translate("ClientUpdateDialog", "含有"))
        self.ctelcomboBox.setItemText(1, _translate("ClientUpdateDialog", "是"))
        self.ctelcomboBox.setItemText(2, _translate("ClientUpdateDialog", "为空"))
        self.label_3.setText(_translate("ClientUpdateDialog", "更改情况"))
        self.idcheckBox.setText(_translate("ClientUpdateDialog", "身份证号"))
        self.namecheckBox.setText(_translate("ClientUpdateDialog", "姓名"))
        self.addresscheckBox.setText(_translate("ClientUpdateDialog", "地址"))
        self.telcheckBox.setText(_translate("ClientUpdateDialog", "联系方式"))
        self.cnamecheckBox.setText(_translate("ClientUpdateDialog", "联系人姓名"))
        self.relationcheckBox.setText(_translate("ClientUpdateDialog", "与联系人关系"))
        self.cemailcheckBox.setText(_translate("ClientUpdateDialog", "联系人邮箱"))
        self.ctelcheckBox.setText(_translate("ClientUpdateDialog", "联系人联系方式"))

