# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TablePage(object):
    def setupUi(self, TablePage):
        TablePage.setObjectName("TablePage")
        TablePage.resize(817, 790)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TablePage.sizePolicy().hasHeightForWidth())
        TablePage.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(TablePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3.addLayout(self.verticalLayout, 5, 0, 2, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.table)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ClientBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ClientBtn.setObjectName("ClientBtn")
        self.gridLayout_2.addWidget(self.ClientBtn, 3, 0, 1, 1)
        self.BusinessBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BusinessBtn.setObjectName("BusinessBtn")
        self.gridLayout_2.addWidget(self.BusinessBtn, 5, 0, 1, 1)
        self.SearchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SearchBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.SearchBtn.setFont(font)
        self.SearchBtn.setObjectName("SearchBtn")
        self.gridLayout_2.addWidget(self.SearchBtn, 0, 0, 1, 1)
        self.ClearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ClearBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ClearBtn.setFont(font)
        self.ClearBtn.setObjectName("ClearBtn")
        self.gridLayout_2.addWidget(self.ClearBtn, 1, 0, 1, 1)
        self.StatisticsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StatisticsBtn.setObjectName("StatisticsBtn")
        self.gridLayout_2.addWidget(self.StatisticsBtn, 6, 0, 1, 1)
        self.AccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccountBtn.setObjectName("AccountBtn")
        self.gridLayout_2.addWidget(self.AccountBtn, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 8, 0, 1, 1)
        TablePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TablePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 24))
        self.menubar.setObjectName("menubar")
        self.Connect = QtWidgets.QMenu(self.menubar)
        self.Connect.setObjectName("Connect")
        TablePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TablePage)
        self.statusbar.setObjectName("statusbar")
        TablePage.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(TablePage)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(TablePage)
        self.actionLogout.setObjectName("actionLogout")
        self.Connect.addAction(self.actionLogin)
        self.Connect.addAction(self.actionLogout)
        self.menubar.addAction(self.Connect.menuAction())

        self.retranslateUi(TablePage)
        QtCore.QMetaObject.connectSlotsByName(TablePage)

    def retranslateUi(self, TablePage):
        _translate = QtCore.QCoreApplication.translate
        TablePage.setWindowTitle(_translate("TablePage", "DataBase ShowTable"))
        self.title.setText(_translate("TablePage", "All The Tables in Database - "))
        self.ClientBtn.setText(_translate("TablePage", "Client"))
        self.BusinessBtn.setText(_translate("TablePage", "Business"))
        self.SearchBtn.setText(_translate("TablePage", "Search"))
        self.ClearBtn.setText(_translate("TablePage", "Clear"))
        self.StatisticsBtn.setText(_translate("TablePage", "Statistics"))
        self.AccountBtn.setText(_translate("TablePage", "Account"))
        self.Connect.setTitle(_translate("TablePage", "连接"))
        self.actionLogin.setText(_translate("TablePage", "Login"))
        self.actionLogout.setText(_translate("TablePage", "Logout"))

